
alternate: SyouSanGin
auto_scroll: true

# 是否显示页面加载动画 loading-cat
loader:
  start: true # 当初次打开页面时，显示加载动画
  switch: false # tab 切换到其他页面时，显示加载动画

fireworks:
  enable: true # 是否启用
  color: # 烟花颜色
    - "rgba(255,182,185,.9)"
    - "rgba(250,227,217,.9)"
    - "rgba(187,222,214,.9)"
    - "rgba(138,198,209,.9)"

font:
  enable: true
  # Font options:
  # `external: true` will load this font family from `host` above.
  # `family: Times New Roman`. Without any quotes.
  # `size: x.x`. Use `em` as unit. Default: 1 (16px)

  # Global font settings used for all elements inside <body>.
  global:
    external: true
    family: Mulish
    size:

  # Font settings for alternate title.
  logo:
    external: true
    family: Fredericka the Great
    size: 3.5

  # Font settings for site title.
  title:
    external: true
    family: Noto Serif JP
    size: 2.5

  # Font settings for headlines (<h1> to <h6>).
  headings:
    external: true
    family: Noto Serif SC
    size:

  # Font settings for posts.
  posts:
    external: true
    family:

  # Font settings for <code> and code blocks.
  codes:
    external: true
    family: Inconsolata
  
# project of https://www.iconfont.cn/
# //at.alicdn.com/t/font_1832207_c8i9n1ulxlt.css => 1832207_c8i9n1ulxlt
iconfont: "1832207_c8i9n1ulxlt"

menu:
  home: / || home
  about: /about/ || user
  posts:
    default: / || feather
    archives: /archives/ || list-alt
    categories: /categories/ || th
    tags: /tags/ || tags
  # friends: /friends/ || heart
  # links: /links/ || magic

social:
  github: https://github.com/syousangin || github || "#191717"
  #google: https://plus.google.com/yourname || google
  #twitter: https://twitter.com/yourname || twitter || "#00aff0"
  zhihu: https://www.zhihu.com/people/agno3-98-25 || zhihu || "#1e88e5"
  music: https://music.163.com/#/user/home?id=531802802 || cloud-music || "#e60026"
  #weibo: https://weibo.com/yourname || weibo || "#ea716e"
  #about: https://about.me/yourname || address-card || "#3b5998"
  #email: mailto:yourname@mail.com || envelope || "#55acd5"
  #facebook: https://www.facebook.com/syousangin || facebook
  stackoverflow: https://stackoverflow.com/users/17616347/syousangin || stack-overflow
  #youtube: https://youtube.com/yourname || youtube
  #instagram: https://instagram.com/yourname || instagram
  #skype: skype:yourname?call|chat || skype
  #douban: https://www.douban.com/people/yourname/ || douban
  # t: https://t.me/syousangin || t || "#55acd5"


sidebar:
  # Sidebar Position.
  position: left
  #position: right
  # Replace the default avatar image and set the url here.
  avatar: avatar.jpg

widgets:
  random_posts: true # 显示随机文章
  recent_comments: false # 显示最近评论

audio:
  - https://music.163.com/song?id=28151022
  - https://music.163.com/song?id=22809860
  - https://music.163.com/song?id=28151054
  - https://music.163.com/song?id=22809865
  - https://music.163.com/song?id=608667
  - https://music.163.com/song?id=608669
  - https://music.163.com/song?id=760528
  - https://music.163.com/song?id=760533
  - https://music.163.com/song?id=22707009
  - https://music.163.com/song?id=26131402
  - https://music.163.com/song?id=26121244
  - https://music.163.com/song?id=26134237
  - https://music.163.com/song?id=26121243
  - https://music.163.com/song?id=26121245
  - https://music.163.com/song?id=22809908
  - https://music.163.com/song?id=608693
  - https://music.163.com/song?id=608697
  - https://music.163.com/song?id=608700
  - https://music.163.com/song?id=608650 
